-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 03:12:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema travel_assistant_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travel_assistant_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_assistant_db` DEFAULT CHARACTER SET utf8 ;
USE `travel_assistant_db` ;

-- -----------------------------------------------------
-- Table `travel_assistant_db`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_assistant_db`.`token` (
  `alg` VARCHAR(45) NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  `iss` VARCHAR(45) NOT NULL,
  `aud` VARCHAR(45) NOT NULL,
  `sub` INT UNSIGNED NOT NULL,
  `jti` VARCHAR(45) NOT NULL,
  `iat` INT NOT NULL,
  `nbf` INT NOT NULL,
  `exp` INT NOT NULL,
  `sig` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`sub`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
